build: false
skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "10"

cache:
  - node_modules
  - _target
  - C:\Users\appveyor\.rustup
  - C:\Users\appveyor\.cargo

configuration: Release
platform:
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - SET PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm run submodule
  - mv _target deltachat-core-rust/target
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - node --version
  - npm --version
  - npm i
  - mv deltachat-core-rust/target _target

test_script:
  - npm test
  - npm run test-integration

before_deploy:
  - SET ARCHIVE_NAME=%APPVEYOR_REPO_TAG_NAME%-win32-x64.tar.gz
  - npm run prebuild
  - tar -zcvf "%ARCHIVE_NAME%" -C prebuilds .
  - appveyor PushArtifact %ARCHIVE_NAME%

deploy:
  - provider: GitHub
    artifact: $(ARCHIVE_NAME)
    auth_token:
      secure: iY0PIcxaGMkJLcAnVJv/VlnGGxPQAa2FqsuN3/fcVjvxosfv4P8b4bYyQqM8NJkg
    draft: false
    on:
      appveyor_repo_tag: true